# Use root/example as user/password credentials
version: '3.1'

services:

  mongo1:
    image: mongo:3.2.21
    command: mongod --config /etc/mongo/mongodb.conf
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./conf:/etc/mongo"
      - "./mongo1/data:/data/db"
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:3.2.21
    command: mongod -f /etc/mongo/mongodb.conf
    restart: always
    volumes:
      - "./conf:/etc/mongo"
      - "./mongo2/data:/data/db"

  mongo3:
    image: mongo:3.2.21
    command: mongod -f /etc/mongo/mongodb.conf
    restart: always
    volumes:
      - "./conf:/etc/mongo"
      - "./mongo3/data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongo1
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo1
